### ISSUE TITLE
HTTPS request fails

### ISSUE THREAD

**Issue by Mirodin** [squeek502/coro-http-luv#2]
Version: 3.1.0 (from Luarocks)
Lua version: 5.3

**How to reproduce:**
Running the [example script](https://github.com/squeek502/coro-http-luv#usage) but replaced `http://localhost/` with `https://example.com` (or any other page using SSL).

**Error message:**
```
Uncaught Error: ./coro-http-luv/coro-net.lua:32: ./coro-http-luv/secure-socket/context.lua:58: bad argument #1 to 'ctx_new' (only support TLS, DTLS to negotiate highest available SSL/TLS or DTLS version above openssl v1.1.0
optional followed by _client or _server
default is TLS
)
stack traceback:
	[C]: in function 'assert'
	./coro-http-luv/coro-net.lua:32: in function <./coro-http-luv/coro-net.lua:25>
	[C]: in function 'luv.run'
	./test.lua:22: in main chunk
	[C]: in ?
```

**Comment by squeek502** [comment]
I believe this is https://github.com/luvit/lit/pull/272

Will try to sync everything back up with the latest lit deps soon.

**Comment by squeek502** [comment]
Should be fixed in latest version (1.1.0-0 on LuaRocks).

**Comment by Mirodin** [comment]
I just pulled 1.1.0-0 from LuaRocks but the error persists. I thought the issue was my Luarocks install so I removed the package and did a git clone but got the same result.

**Comment by squeek502** [comment]
What version of openssl/lua-openssl are you using? Could you post the result of running:

```
lua -e "print((require 'openssl').version())"
```

**Comment by Mirodin** [comment]
Sorry for the late reply. I do not longer have access to the machine I used back then. My new machine running Void does not exhibit this problem any more so I think we can close this issue.
